name: Lab02-Workflows
on:
  workflow_dispatch:
  push:
    branches:
        - "main"
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3 #Use checkout action to download the source code to run unittest
          name: Checkout
        - uses: actions/setup-go@v3 #Setup golang environment for runnint unittest
          name: Setup Go environment
          with:
            go-version-file: ./src/go.mod
        - name: Prepare Unit Test
          working-directory: ./src
          run: go mod download
        - name: Run Unit Test
          working-directory: ./src
          run: go test ./... -coverprofile="coverage.out" -v
        - name: list file
          working-directory: ./src
          run: ls -l
  code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3 #Use checkout action to download the source code to run unittest
            name: Checkout
          - uses: actions/setup-go@v3 #Setup golang environment for runnint unittest
            name: Setup Go environment
            with:
              go-version-file: ./src/go.mod
          - name: Run Code Coverage checking
            run: go test ./... -coverprofile=coverage.out 
          - name: Reformat coverage report
            run: go tool cover -func coverage.out -o coverage.txt
          - name: Print out report
            working-directory: ./src
            run: cat coverage.txt
          - name: Upload coverage report to artifact
            uses: actions/upload-artifact@v3
            with:
              name: code-coverage-report
              path: src/coverage.txt